# Generated by Django 3.2 on 2021-08-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('category', models.CharField(max_length=15, verbose_name='Категория')),
                ('date', models.CharField(max_length=20, verbose_name='Дата публикации')),
                ('text', models.CharField(blank=True, max_length=16777215, null=True, verbose_name='Текст статьи')),
                ('tags', models.CharField(blank=True, max_length=400, null=True, verbose_name='Теги')),
                ('keyWords', models.CharField(blank=True, max_length=400, null=True, verbose_name='Ключевые слова')),
                ('url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка')),
            ],
        ),
    ]
