# Generated by Django 3.2 on 2021-05-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fstName', models.CharField(max_length=40, verbose_name='Student name')),
                ('secName', models.CharField(max_length=80, verbose_name='Student surname')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Student patronymic')),
                ('averageMark', models.FloatField(verbose_name='Average mark')),
            ],
        ),
    ]
